services:
  - type: web
    name: speedy-finance-backend
    runtime: docker
    rootDir: python-services
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DEBUG
        value: "False"
    healthCheckPath: /health
